week8_solutions
hayrunnisa00/weekly-JavaTasks pull request #33
Opened 2023-12-29 18:09 UTC by srestr53

2024-01-02 02:17 UTC, hayrunnisa00 approved these changes

2024-01-02 13:20 UTC, vandalat requested changes

2024-01-02 13:20 UTC, vandalat commented on src/week_08/ZerosToEnd.java
good job Santi

2024-01-02 13:20 UTC, vandalat commented on src/week_08/IntSum_0.java
![Screenshot 2024-01-02 071657](https://github.com/hayrunnisa00/weekly-JavaTasks/assets/140336926/5096e3b1-d8db-4a39-a2bc-99525902ec8e)
please check this code. i copy and paste in my interliJ >> it doesn't return for me any array as picture i attached

2024-01-03 17:22 UTC, hayrunnisa00 approved these changes

2024-01-13 11:03 UTC, vandalat approved these changes

2024-01-13 11:03 UTC, merged